language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install flake8
  - pip install -r tests/requirements.txt
# check PEP8 coding standard with flake8
before_script:
   flake8 .
# command to run tests
script: python -m unittest tests.testall
